<#
Auto-Generated by New-FunctionTest, a PSChuck tool.

Created on %%DATE%%
#>


$functionName = "%%FUNCTION_NAME%%"

if( ($psScriptRoot -match ("\\Test\\|\\Tests\\") ) {
    $functionPath = Get-ChildItem -path $psScriptRoot\.. -filter "$($functionName).ps1" -recurse
    $function = . "$(functionPath.FullName)"
}
else {
    $function = . "$($psScriptRoot)\$($functionName).ps1"
}

Describe "%%FUNCTION_NAME%%" {
    Context "Parameter Validation"{
    
        %%ParamBasics%%
    
    }
    
    Context "Expected Behavior" {
    
        %%ExpectedBehavior%%
        
    }
    
}